# Generated by Django 4.1.4 on 2023-06-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('depressive', models.FloatField(default=0)),
                ('suicide', models.FloatField(default=0)),
                ('cyberbullying', models.FloatField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'person',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_related_name': 'person',
            },
        ),
    ]
