# Generated by Django 4.1.4 on 2023-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='graph_cyb',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_dep',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_home',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_sui',
            field=models.TextField(default='[]'),
        ),
    ]
