# Generated by Django 4.1.4 on 2023-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_remove_person_graph_cyb_remove_person_graph_dep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='graph_cyb',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_dep',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_home',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='graph_sui',
            field=models.JSONField(default=list),
        ),
    ]
